include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  errors: 
    invalid_annotation_target: ignore

custom_lint:
  rules:
    - missing_provider_scope: false

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
