targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**/models/**.dart
      go_router_builder:
         generate_for:
          include:
            - lib/**/router/**.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/**/router/**.dart
            - lib/**/controllers/**.dart
            - lib/**/providers/**.dart
