name: luckuveryx
description: LuckUVeryX
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  hooks_riverpod: ^2.4.9
  intl: ^0.18.0
  lottie: ^2.7.0
  posthog_flutter: ^3.3.0
  riverpod_annotation: ^2.3.3
  styled_text: ^8.1.0
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.0
  mocktail: ^1.0.2
  riverpod_generator: ^3.0.0-dev.3
  riverpod_lint: ^2.3.4
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/lottie/
  fonts:
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-UltraLight.otf
          weight: 100
        - asset: assets/fonts/GeistMono-Light.otf
          weight: 200
        - asset: assets/fonts/GeistMono-Regular.otf
          weight: 300
        - asset: assets/fonts/GeistMono-Medium.otf
          weight: 400
        - asset: assets/fonts/GeistMono-SemiBold.otf
          weight: 500
        - asset: assets/fonts/GeistMono-Bold.otf
          weight: 600
        - asset: assets/fonts/GeistMono-Black.otf
          weight: 700
        - asset: assets/fonts/GeistMono-UltraBlack.otf
          weight: 800
        - asset: assets/fonts/GeistMono-UltraBlack.otf
          weight: 900
  generate: true
  uses-material-design: true

flutter_gen:
  integrations:
    lottie: true
