name: luckuveryx
description: LuckUVeryX
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  go_router: ^11.1.4
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.4
  intl: ^0.18.0
  riverpod_annotation: ^2.2.1
  styled_text: ^8.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.3
  mocktail: ^1.0.0
  riverpod_generator: ^3.0.0-dev.4
  riverpod_lint: ^2.3.1
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
