name: luckuveryx
description: LuckUVeryX
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.4.3
  intl: ^0.18.0
  riverpod_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  riverpod_generator: ^3.0.0-dev.3
  riverpod_lint: ^2.3.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
