name: luckuveryx

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      min_coverage: 0
      setup: |
        flutter pub run build_runner build --delete-conflicting-outputs
        flutter pub get
